### ISSUE TITLE
Google reCaptcha - locked out forever?

### ISSUE THREAD

**Issue by akdsco** [Arsenal21/all-in-one-wordpress-security#102]
Hello Team,

I've just tried to switch from mathematical login captcha to google reCaptcha on my website that uses all-in-one-wordpress-security plugin. After I've done the switch in settings on my site, I logged out and tried to test it. The login form came back with email and password inputs but no captcha at all. After typing in my password (I use password manager, so no room for the mistake) I could not log back in. Now, because I set failed attempts to 3 and then redirection to localhost, I can't even try to genuinely log back in. I have access to cPanel and can log in, however, there's still a problem that the plugin either does not display google reCaptcha but does need it for verification, therefore, any login attempt will be rejected. Is there any way I can change captcha settings through cPanel access? Is there any other back door to by-pass captchas and log in to change the badly working setting?

Thanks
Arkadiusz

**Comment by JakubJeziorski** [comment]
Hey Akradiusz (Witaj )

Not sure if it is still needed (probably not) but for other people who have the same issue:
https://www.tipsandtricks-hq.com/deactivate-wordpress-plugins-without-logging-into-wp-admin-video-tutorial-4375

**Comment by akdsco** [comment]
Hello (Czesc),

Yes, got out eventually, forgot about this ticket. Thanks for the link, some future travellers might need it 🙂
