### ISSUE TITLE
Problem with auto-logout feature and redirect_to query argument

### ISSUE THREAD

**Issue by chesio** [Arsenal21/all-in-one-wordpress-security#11]
Hello,

I noticed that AIOWPS plugin **does not** [urlencode](http://php.net/manual/en/function.urlencode.php) values of `redirect_to` query argument, despite that the argument contains full URLs (often with their own query arguments). 

This results in at least the following two problems:

1) If I have "Block Bad Query Strings" firewall rules active and I am auto-logged when trying to access some admin page, I face "403 forbidden" error instead of _wp-login.php_. The reason is the "Block Bad Query Strings" rules catch on "http:" (or "https:") in `redirect_to` argument appended to _wp-login.php_ URL by AIOWPS.

2) If I don't have "Block Bad Query Strings" active and I am auto-logged when trying to access admin page that has URL with **more than one** query string argument, like for example http://www.example.com/wp-admin/comment.php?action=spam&c=123, I have another problem: the login page URL becomes http://www.example.com/wp-login.php?redirect_to=http://www.example.com/wp-admin/comment.php?action=spam&c=123&aiowps_login_msg_id=session_expired Notice that the `c` query argument is no longer part of `redirect_to` argument value, but becomes query argument on its own! So after I am loggged in, I am redirected to http://www.example.com/wp-admin/comment.php?action=spam instead of http://www.example.com/wp-admin/comment.php?action=spam&c=123.

The url encoding would prevent both issues:

1) The "http:" string would become "http%3A" and will not trigger firewall rule anymore.

2) Obviously :)

I think you only need to fix your [helper method](https://github.com/Arsenal21/all-in-one-wordpress-security/blob/master/all-in-one-wp-security/classes/wp-security-utility.php#L103) to fix the problem (if you use it consistently within your code). If in doubt, consult WordPress core codebase - WP core sets the `redirect_to` argument properly ;)

Best regards,
Česlav

**Comment by wpsolutions** [comment]
Thanks for pointing this out Česlav.
We will apply a fix.
