### ISSUE TITLE
Admin username can easily be found

### ISSUE THREAD

**Issue by ardalann** [Arsenal21/all-in-one-wordpress-security#3]
Many hackers who try to find the admin pass via a Brute Force login attack, find the admin username by entering the following URL: http://wordpresssite.com/?author=1
On most WP permalink setups, this will redirect to a URL like: http://ardalan.me/en/author/ADMINUSER/

Maybe in the User Accounts settings page, we should change the main admin ID as well. What do you think?

**Comment by ardalann** [comment]
@Arsenal21 Closed with no comment?

**Comment by Arsenal21** [comment]
There is now a new feature in the plugin that you can enable which prevents URLs like "?author=1" from working. You can find this feature in the following interface: 

Miscellaneous -> User Enumeration

**Comment by ardalann** [comment]
Thank you @Arsenal21 .
