### ISSUE TITLE
Plugin log files are emptied on plugin update...

### ISSUE THREAD

**Issue by chesio** [Arsenal21/all-in-one-wordpress-security#55]
...because they are kept inside plugin's directory. A solution would be to store log files in `wp-content/aiowps_logs` or similar.

**Comment by Arsenal21** [comment]
The purpose of the log file is to debug an issue on a site that maybe showing a weird behavior. It is not to be kept on all the time. So the files are suppose to be temporary. We also want to remove the file every now and then (removing it on every upgrade does the job). 

If someone is trying to use the log file for something else then that person is not using it for the intended purpose. Maybe there can be a different new feature to add functionality to cover that person's need.

**Comment by chesio** [comment]
Ok, I see. Makes sense. I would just suggest to add some more information to AIOWPS log tab:

- a short (permanent) message: "Log files are reset on every plugin update."
- a notice/warning saying "Logs are populated only if you enable debugging." that shows up if debugging is currently disabled in settings.

This could help avoid confusion over why [logs seems (always) empty](https://wordpress.org/support/topic/log-files-always-empty/).

**Comment by Arsenal21** [comment]
Sounds good. I will add a message/notice for this.
