### ISSUE TITLE
block access to wp-content/debug.log

### ISSUE THREAD

**Issue by ziodave** [Arsenal21/all-in-one-wordpress-security#6]
WordPress has an option to turn on the [debug logging](https://codex.wordpress.org/Debugging_in_WordPress#WP_DEBUG_LOG) to a file located in `wp-content/debug.log`. This file may contain sensitive information.

I propose that an option is provided to the plugin users to block access to this file (by means of `.htaccess` configuration).

**Comment by Arsenal21** [comment]
We will add an option for this.

**Comment by Arsenal21** [comment]
A new feature has been added to the plugin for this.
